site_name: SignalFlow

site_description: "SignalFlow is a sound synthesis framework designed for exploring complex sonic ideas."
repo_name: ideoforms/signalflow
repo_url: https://github.com/ideoforms/signalflow

theme:
  name: material
  palette:
   - primary: red
  features:
   # enable button to copy code block
   - content.code.copy
   # expand all navigation sections on large screens
   - navigation.sections
   # breadcrumbs (not yet available, to arrive in a future version)
   - navigation.path
   # allow each section's title to be a hyperlinked index page
   - navigation.indexes
   # "back to top" button
   - navigation.top
   # footer with next/previous links
   - navigation.footer
  font:
    text: "IBM Plex Sans"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ideoforms
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ideoforms

markdown_extensions:
 - admonition
 - attr_list
 - pymdownx.tabbed
 - pymdownx.highlight
 - pymdownx.superfences

plugins:
 - include-markdown
 - search

nav:
 - Home:
   - Home: index.md
 - Getting started:
   - Getting started: installation/index.md
   - Installation:
     - Installation: installation/index.md
     - Installing on macOS:
        - Easy install: installation/macos/easy.md
        - Command-line installation: installation/macos/command-line.md
     - Installing on Linux:
        - Command-line installation: installation/linux/command-line.md
   - Examples: examples.md
   - License: license.md
 - Reference library:
     - Reference library: library/index.md
 - The AudioGraph:
    - The AudioGraph: graph/index.md
    - Creating the graph: graph/creating.md
    - Configuration: graph/config.md
    - Status and properties: graph/properties.md
    - Recording the audio output: graph/recording.md
    - Stopping the graph: graph/stopping.md
 - Nodes:
    - Nodes: node/index.md
    - Playback: node/playback.md
    - Inputs: node/inputs.md
    - Operators: node/operators.md
    - Multichannel: node/multichannel.md
    - Status and properties: node/properties.md
    - Stochastic nodes: node/stochastic.md
    - Developing a new Node class: node/developing.md
 - Patches:
    - Patches: patch/index.md
    - Defining a Patch: patch/defining.md
    - Playback: patch/playback.md
    - Inputs: patch/inputs.md
    - Operators: patch/operators.md
    - Properties: patch/properties.md
    - Exporting and importing patches: patch/exporting.md
    - Auto-free and memory management: patch/auto-free.md
 - Buffers:
    - Buffers: buffer/index.md

