site_name: SignalFlow
theme:
  name: material
  features:
   - navigation.tabs

repo_name: ideoforms/signalflow
repo_url: https://github.com/ideoforms/signalflow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ideoforms
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ideoforms

markdown_extensions:
 - admonition
 - pymdownx.tabbed
 - pymdownx.highlight
 - pymdownx.superfences

nav:
 - Home:
   - Home: index.md
   - Getting started: getting-started.md
   - Examples: examples.md
   - License: license.md
 - The AudioGraph:
    - The AudioGraph: graph/index.md
    - Creating the graph: graph/creating.md
    - Configuration: graph/config.md
    - Status and properties: graph/properties.md
    - Recording the audio output: graph/recording.md
    - Stopping the graph: graph/stopping.md
 - Nodes:
    - Nodes: node/index.md
    - Playback: node/playback.md
    - Inputs: node/inputs.md
    - Operators: node/operators.md
    - Multichannel: node/multichannel.md
    - Status and properties: node/properties.md
    - Stochastic nodes: node/stochastic.md
    - Reference library: node/library.md
    - Developing a new Node class: node/developing.md
 - Buffers:
    - Buffers: buffer/index.md
 - Patches:
    - Patches: patch/index.md
