site_name: "SignalFlow: Python sound synthesis and DSP"
site_description: "SignalFlow is a sound synthesis framework designed for exploring complex sonic ideas."
repo_name: ideoforms/signalflow
repo_url: https://github.com/ideoforms/signalflow

theme:
  name: material
  palette:
   - primary: pink
  features:
   - content.code.copy


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ideoforms
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ideoforms

markdown_extensions:
 - admonition
 - attr_list
 - pymdownx.tabbed
 - pymdownx.highlight
 - pymdownx.superfences

nav:
 - Home:
   - Home: index.md
   - Getting started: getting-started.md
   - Installation:
     - Installing on macOS:
        - Easy install: installation/macos/easy.md
        - Command-line installation: installation/macos/command-line.md
     - Installing on Linux: installation/linux.md
   - Examples: examples.md
   - License: license.md
 - The AudioGraph:
    - The AudioGraph: graph/index.md
    - Creating the graph: graph/creating.md
    - Configuration: graph/config.md
    - Status and properties: graph/properties.md
    - Recording the audio output: graph/recording.md
    - Stopping the graph: graph/stopping.md
 - Nodes:
    - Nodes: node/index.md
    - Playback: node/playback.md
    - Inputs: node/inputs.md
    - Operators: node/operators.md
    - Multichannel: node/multichannel.md
    - Status and properties: node/properties.md
    - Stochastic nodes: node/stochastic.md
    - Developing a new Node class: node/developing.md
    - Reference library: node/library.md
 - Patches:
    - Patches: patch/index.md
    - Defining a Patch: patch/defining.md
    - Playback: patch/playback.md
    - Inputs: patch/inputs.md
    - Operators: patch/operators.md
    - Properties: patch/properties.md
    - Exporting and importing patches: patch/exporting.md
    - Auto-free and memory management: patch/auto-free.md
 - Buffers:
    - Buffers: buffer/index.md

