name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo rm -rf /home/linuxbrew
        sudo apt-get update -y
        sudo apt-get install libasound2-dev libsoundio-dev libsndfile1-dev libgsl0-dev -y
        sudo apt-get install python3 python3-setuptools python3-pip python3-numpy
        sudo pip3 install pytest
    - name: Configure
      run: mkdir build && cd build && cmake ..
    - name: Make
      run: cd build && make -j8
    - name: Python build
      run: python3.7 setup.py build
    - name: Python test
      run: python3.7 setup.py test
