name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libasound2-dev libsoundio-dev libsndfile1-dev libgsl0-dev -y
    - name: Configure
      run: mkdir build && cd build && cmake ..
    - name: Make
      run: cd build && make -j8
    - name: Python build
      python3 setup.py build
    - name: Python test
      python3 setup.py test
